services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: ng serve --host 0.0.0.0
    networks:
      - my-network

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend::/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    networks:
      - my-network

networks:
  my-network:
    driver: bridge