services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
      - WATCHPACK_POLLING=${WATCHPACK_POLLING}
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run build && npx http-server dist -p ${FRONTEND_PORT}
    networks:
      - my-network

  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
      - WATCHPACK_POLLING=${WATCHPACK_POLLING}
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

# Dockerizing for production
# docker-compose --env-file .env.prod -f docker-compose.prod.yml up --build
